version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
executors:
  java-build:
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx512m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=true"
      STACK_VER: << pipeline.number >>

    docker:
      - image: cimg/openjdk:21.0

common_steps: &common_steps
  steps:
    - add_ssh_keys:
        fingerprints:
          - "7e:93:fb:39:b3:21:f7:b6:48:bd:f7:0e:56:5c:ad:87"
    - checkout
    - restore_cache:
        keys:
          - v2-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-data/build.gradle" }}-{{ checksum "~/project/jar-shell/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}
    - save_cache:
        paths:
          - ~/.gradle
        key: v2-build-cache-{{ checksum "~/project/jar-common/build.gradle" }}-{{ checksum "~/project/svc-data/build.gradle" }}-{{ checksum "~/project/jar-shell/build.gradle" }}-{{ checksum "~/project/svc-position/build.gradle" }}
    - save_cache:
        paths:
          - ~/.m2
          - ~/.gradle
          - ~/project
        key: v1-sha-cache-{{ .Environment.CIRCLE_SHA1 }}
    - persist_to_workspace:
        root: ~/project
        paths:
          - ./jar-common/build/reports/jacoco/test/*.xml
          - ./codecov.yml

jobs:
  build-common:
    executor: java-build
    resource_class: large
    environment:
      IMAGE_NAME: bc-common
    <<: *common_steps
    steps:
      - run: './gradlew jar-common:build'
      - codecov/upload:
          file: ./jar-common/build/reports/jacoco/test/jacocoTestReport.xml
      - store_artifacts:
          path: ~/project/jar-common/build/libs

  build-client:
    executor: java-build
    resource_class: large
    environment:
      IMAGE_NAME: bc-client
    <<: *common_steps
    steps:
      - run: './gradlew jar-client:build'
      - codecov/upload:
          file: ./jar-client/build/reports/jacoco/test/jacocoTestReport.xml
      - store_artifacts:
          path: ~/project/jar-client/build/libs

  # Add more jobs as needed...

workflows:
  version: 2
  build_and_stage:
    jobs:
      - build-common
      - build-client
      # Add more jobs as needed...
      - publish-coverage:
          filters:
            branches:
              only:
                - master
                - /^codacy.*/
          requires:
            - build-common
            - build-client
            # Add more jobs as needed...
