version: '3.5'
services:
  shell:

    # Create a symbolic link to where your secrets are stored
    #  ln -s ../secrets/ ./secrets
    # docker-compose -f shell.yml run --rm shell

    image: monowai/bc-shell
    container_name: shell
    #stdin_open: true
    #tty: true
    ports:
      - 9690:9690

    environment:
      MARKETDATA_URL: "http://data:9510/api"
      AUTH_URI: "http://keycloak:8080/auth"
      API_PATH: "/secrets/google-api/"
      API_PORT: 9690

    command: ["./wait-for-it.sh", "data:9611"]
    volumes:
      - ../secrets:/secrets

