auth:
  enabled: false
  web: false
beancounter:
  market:
    providers:
      mock:
        markets: MOCK

      alpha:
        url: https://www.alphavantage.co
        batchSize: 1
        markets: NASDAQ,AMEX,NYSE,NZX,ASX

#      mstack:
#        url: https://www.worldtradingdata.com
#        batchSize: 2
#        markets: NASDAQ,AMEX,NYSE,NZX,ASX

logging:
  level:
    root: trace
    org.springframework.security: error


